# Generated by Django 4.0.2 on 2022-03-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vt_owner',
            fields=[
                ('regn_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=35)),
                ('regn_dt', models.DateField(max_length=10)),
                ('no_cyl', models.IntegerField()),
            ],
        ),
    ]
