# Generated by Django 4.0.2 on 2022-03-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypostgresapp', '0002_alter_vt_owner_regn_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='vm_vh_class',
            fields=[
                ('code', models.IntegerField(max_length=3, primary_key=True, serialize=False)),
                ('descr', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='vt_owner',
            name='vh_class',
            field=models.IntegerField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
