# Generated by Django 4.0.2 on 2022-03-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypostgresapp', '0003_vm_vh_class_vt_owner_vh_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vm_vh_class',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vt_owner',
            name='vh_class',
            field=models.IntegerField(),
        ),
    ]
