# Generated by Django 4.0.2 on 2022-03-08 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypostgresapp', '0004_alter_vm_vh_class_code_alter_vt_owner_vh_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='vt_owner',
            name='fk_vh_class',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mypostgresapp.vm_vh_class'),
        ),
        migrations.AlterField(
            model_name='vm_vh_class',
            name='code',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vm_vh_class',
            name='descr',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
