# Generated by Django 4.0.2 on 2022-03-08 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypostgresapp', '0006_delete_vt_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vm_vh_class',
        ),
    ]
