# Generated by Django 4.0.2 on 2022-03-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypostgresapp', '0010_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm_vh_class',
            name='transport_catg',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
    ]
