# Generated by Django 4.0.2 on 2022-03-08 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypostgresapp', '0011_vm_vh_class_transport_catg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vt_owner',
            name='vh_class',
        ),
        migrations.DeleteModel(
            name='vm_vh_class',
        ),
        migrations.DeleteModel(
            name='vt_owner',
        ),
    ]
